language: node_js

node_js: node

cache:
  directories:
    - node_modules

script: yarn

jobs:
  include:
    - stage: release
      node_js: lts/*
      deploy:
        provider: script
        skip_cleanup: true
        script: yarn semantic-release
